import turtle
weather_size = 100
weather = input("What is the weather?(sunny, cloudy, rainy, or snowy)")

#Create new t
t = turtle.Turtle()
t.hideturtle()
turtle.bgcolor("sky blue")

t.penup()
if weather == "sunny":
    t.setposition(0 * weather_size, 1 * weather_size)
    t.color("yellow")
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
elif weather == "cloudy":
    t.setposition(1.5 * weather_size, 1.4 * weather_size)
    t.color("yellow")
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()
    t.setposition(1 * weather_size, 0 * weather_size)
    t.color("white")
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()
    t.setposition(-0.4 * weather_size, 1 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()
    t.setposition(-0.25 * weather_size, -0.7 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()
    t.setposition(-1.5 * weather_size, 0 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()
elif weather == "snowy":
    t.setposition(1 * weather_size, 0 * weather_size)
    t.color("white")
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()
    t.setposition(-0.4 * weather_size, 1 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()
    t.setposition(-0.25 * weather_size, -0.7 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()
    t.setposition(-1.5 * weather_size, 0 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()

    #drops
    t.setposition(0 * weather_size, -1 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size * 0.10)
    t.end_fill()
    t.penup()
    t.setposition(1.2 * weather_size, -1.2 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size * 0.10)
    t.end_fill()
    t.penup()
    t.setposition(-1.4 * weather_size, -1.4 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size * 0.10)
    t.end_fill()
    t.penup()
    t.setposition(0.4 * weather_size, -2 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size * 0.10)
    t.end_fill()
    t.penup()
elif weather == "rainy":
    t.setposition(1 * weather_size, 0 * weather_size)
    t.color("blue")
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()
    t.setposition(-0.4 * weather_size, 1 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()
    t.setposition(-0.25 * weather_size, -0.7 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()
    t.setposition(-1.5 * weather_size, 0 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size)
    t.end_fill()
    t.penup()

    #drops
    t.setposition(0 * weather_size, -1 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size * 0.10)
    t.end_fill()
    t.penup()
    t.setposition(1.2 * weather_size, -1.2 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size * 0.10)
    t.end_fill()
    t.penup()
    t.setposition(-1.4 * weather_size, -1.4 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size * 0.10)
    t.end_fill()
    t.penup()
    t.setposition(0.4 * weather_size, -2 * weather_size)
    t.pendown()
    t.begin_fill()
    t.circle(weather_size * 0.10)
    t.end_fill()
    t.penup()

turtle.done()